apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline-demo
  name: pipeline-demo
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pipeline-demo
    deploymentconfig: pipeline-demo