apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: nodejs-lint
spec:
  inputs: 
    resources:
      - name: source
        type: git
  outputs:
    resources:
      - name: source
        type: git
  steps:
    - name: install
      image: node:12
      command: ["npm", "install"]
      workingDir: /workspace/source/app
    - name: audit
      image: node:12
      command: ["npm", "audit"]
      workingDir: /workspace/source/app
    - name : lint
      image: node:12
      command: ["npm", "run", "lint"]
      workingDir: /workspace/source/app