apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: nodejs-ci
spec:
  inputs: 
    resources:
      - name: source
        type: git
  steps:
    - name: install
      image: node:12
      command: ["npm", "install"]
      workingDir: /workspace/source/app
    - name: test
      image: node:12
      command: ["npm", "test"]
      workingDir: /workspace/source/app
