apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: parallel-pipeline
  labels:
    app: summit-demo
spec:
  resources:
    - name: app-git
      type: git
    - name: app-image
      type: image
  tasks:
    - name: app-test
      taskRef: 
        name: nodejs-ci
      resources:
        inputs:
          - name: source
            resource: app-git
        outputs:
          - name: source
            resource: app-git
    - name: app-lint
      taskRef:
        name: nodejs-lint
      resources: 
        inputs:
          - name: source
            resource: app-git
        outputs:
          - name: source
            resource: app-git
    - name: build
      taskRef:
        name: s2i-nodejs
      resources:
        inputs:
        - name: source
          resource: app-git
          from: 
            - app-lint
            - app-test
        outputs:
        - name: image
          resource: app-image
    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - build
      params:
      - name: ARGS
        value: "rollout latest summit-demo"
