apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: summit-demo-git
  labels:
    app: tekton-workshop
spec:
  type: git
  params:
  - name: url
    value: https://github.com/joellord/summit-demo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: summit-demo-image
  labels:
    app: tekton-workshop
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/lab-tekton/summit-demo:latest